import assert from 'node:assert/strict';
import { withHeadlessBrowser } from './headless.mjs';

await withHeadlessBrowser(async ({ base, call, evaluate, until, delay, fresh, screenshot }) => {
  await fresh('settings');
  await call('Page.navigate', { url: `${base}/tests/browser/mcp-setup.html` });
  await until('Boolean(document.querySelector("#mcp-client"))', 30000);
  const click = text => evaluate(`[...document.querySelectorAll('button')].find(button => button.textContent.trim() === ${JSON.stringify(text)}).click(); mcpSetupTest.tick()`);
  const select = (id, value) => evaluate(`(() => { const element = document.getElementById(${JSON.stringify(id)}); element.value = ${JSON.stringify(value)}; element.dispatchEvent(new Event('change', {bubbles:true})); return mcpSetupTest.tick(); })()`);
  assert.equal(await evaluate('document.querySelector("#mcp-client").value'), 'generic');
  assert.equal(await evaluate(`document.querySelector('input[aria-label="MCP 服务地址"]').value`), 'http://127.0.0.1:34601/mcp');
  assert.ok(await evaluate('document.body.innerText.includes("添加到客户端")'));
  assert.ok(await evaluate('document.body.innerText.includes("验证接入")'));
  await click('复制地址');
  assert.equal(await evaluate('mcpSetupTest.clipboard'), 'http://127.0.0.1:34601/mcp');
  await evaluate('mcpSetupTest.copyFails = true');
  await click('已复制');
  await until('document.body.innerText.includes("复制失败")');
  await evaluate('mcpSetupTest.copyFails = false');
  await select('mcp-client', 'claude');
  await select('mcp-scope', 'project');
  assert.match(await evaluate('document.querySelector("textarea").value'), /--scope local/);
  assert.ok(await evaluate('document.querySelector("#mcp-scope").selectedOptions[0].textContent.includes("仅自己")'));
  await evaluate(`document.querySelector('button[aria-label="复制终端命令"]').click(); mcpSetupTest.tick()`);
  assert.equal(await evaluate('mcpSetupTest.clipboard'), 'claude mcp add --scope local --transport http neoserial http://127.0.0.1:34601/mcp');
  await select('mcp-client', 'codex');
  assert.match(await evaluate('document.querySelector("textarea").value'), /^\[mcp_servers.neoserial\]/);
  await select('mcp-scope', 'user');
  assert.equal(await evaluate('document.querySelectorAll("textarea").length'), 1);
  assert.match(await evaluate('document.querySelector("textarea").value'), /^codex mcp add/);
  await click('手动配置（替代命令）');
  await until('document.querySelectorAll("textarea").length === 2');
  assert.ok(await evaluate('document.body.innerText.includes("保留其他服务")'));
  await select('mcp-client', 'cursor');
  await until('document.querySelectorAll("textarea").length === 1');
  assert.equal(JSON.parse(await evaluate('document.querySelector("textarea").value')).mcpServers.neoserial.url, 'http://127.0.0.1:34601/mcp');
  await select('mcp-client', 'vscode');
  assert.equal(JSON.parse(await evaluate('document.querySelector("textarea").value')).servers.neoserial.type, 'http');
  assert.ok(await evaluate('document.querySelector("#mcp-scope").selectedOptions[0].textContent.includes("配置文件")'));
  await click('复制验证提示词');
  assert.match(await evaluate('mcpSetupTest.clipboard'), /list_ports/);
  assert.match(await evaluate('mcpSetupTest.clipboard'), /不要连接串口/);
  assert.equal(await evaluate('mcpSetupTest.calls.includes("list_ports")'), false);
  await click('本机服务自检');
  await until('document.body.innerText.includes("19 个工具可读取")');
  assert.ok(await evaluate('document.body.innerText.includes("客户端是否接入请在客户端确认")'));
  await evaluate('mcpSetupTest.error = "mock connection unavailable"');
  await click('本机服务自检');
  await until('document.body.innerText.includes("自检失败")');
  await click('接入遇到问题？');
  await until('document.body.innerText.includes("端口变化")');
  await evaluate('mcpSetupTest.status = {running:true,port:34609}');
  await click('刷新状态');
  await until('document.querySelector("textarea")?.value.includes(":34609/")');
  assert.equal(await evaluate('document.body.innerText.includes("自检失败")'), false);
  await evaluate('mcpSetupTest.status = {running:false,port:null}');
  await click('刷新状态');
  await until('document.body.innerText.includes("服务未运行")');
  assert.equal(await evaluate('document.querySelectorAll("textarea").length'), 0);
  await evaluate('mcpSetupTest.status={running:true,port:34609};mcpSetupTest.error="";mcpSetupTest.delay=400;mcpSetupTest.remount()');
  await until('Boolean(document.querySelector("#mcp-client"))');
  await click('本机服务自检');
  await evaluate('mcpSetupTest.status={running:false,port:null};mcpSetupTest.remount()');
  await delay(500);
  assert.ok(await evaluate('document.body.innerText.includes("服务未运行")'));
  assert.equal(await evaluate('document.body.innerText.includes("19 个工具可读取")'), false);
  await call('Emulation.setDeviceMetricsOverride', {width:680,height:780,deviceScaleFactor:1,mobile:false});
  await fresh('settings');
  await evaluate(`persistenceTest.reply('get_mcp_status', {running:true,port:34601}); persistenceTest.reopenSettings({section:'extensions',ext_module:'mcp',anchor:null})`);
  await until('Boolean(document.querySelector("#mcp-client"))');
  await evaluate(`const client = document.querySelector('#mcp-client'); client.value = 'codex'; client.dispatchEvent(new Event('change', {bubbles:true})); persistenceTest.tick()`);
  await screenshot('docs/mcp-onboarding-preview.png');
  await evaluate(`document.querySelector('#mcp-client').scrollIntoView({block:'start'})`);
  await screenshot('docs/mcp-onboarding-steps.png');
  await call('Emulation.setDeviceMetricsOverride', {width:680,height:500,deviceScaleFactor:1,mobile:false});
  assert.ok(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'));
  assert.ok(await evaluate('persistenceTest.button("保存").getBoundingClientRect().bottom <= 500'));
  console.log('PASS MCP onboarding: all scopes, recommended/alternative methods, copy/failure, safe verification prompt, self-check isolation, troubleshooting, actual ports and stale replies');
}, {timeoutMs:180000});
