import assert from 'node:assert/strict';
import { withHeadlessBrowser } from './headless.mjs';

await withHeadlessBrowser(async ({ call, fresh, evaluate, until, click, delay, screenshot }) => {
  await call('Emulation.setFocusEmulationEnabled', { enabled: true });
  await call('Emulation.setDeviceMetricsOverride', { width: 680, height: 500, deviceScaleFactor: 1, mobile: false });
  await fresh('settings');
  await evaluate(`persistenceTest.reopenSettings({section:'extensions',ext_module:'data',anchor:null})`);
  await until('document.body.innerText.includes("帧构造器选项")');
  const trigger = `document.querySelector('button[aria-label="数据处理说明"]')`;
  assert.ok(await evaluate(`Boolean(${trigger})`), 'Module heading has a help button');
  assert.equal(await evaluate('Boolean(document.querySelector("[role=tooltip]"))'), false);
  await evaluate(`${trigger}.dispatchEvent(new PointerEvent('pointerenter')); persistenceTest.tick()`);
  await until('Boolean(document.querySelector("[role=tooltip]"))');
  assert.ok(await evaluate('document.querySelector("[role=tooltip]").textContent.includes("关闭后隐藏数据处理入口")'));
  await evaluate(`${trigger}.dispatchEvent(new PointerEvent('pointerleave'))`);
  await delay(200);
  assert.equal(await evaluate('Boolean(document.querySelector("[role=tooltip]"))'), false);
  await evaluate(`${trigger}.focus(); persistenceTest.tick()`);
  await until('Boolean(document.querySelector("[role=tooltip]"))');
  await call('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape' });
  await until('!document.querySelector("[role=tooltip]")');
  assert.ok(await evaluate('Boolean(persistenceTest.button("保存"))'), 'Escape closes help, not settings');
  await evaluate(`${trigger}.click(); persistenceTest.tick()`);
  await until('Boolean(document.querySelector("[role=tooltip]"))');
  const geometry = await evaluate(`(() => { const rect = document.querySelector('[role=tooltip]').getBoundingClientRect(); return {left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom}; })()`);
  assert.ok(geometry.left >= 0 && geometry.right <= 680 && geometry.top >= 0 && geometry.bottom <= 500);
  await screenshot('docs/settings-help-preview.png');
  await evaluate(`document.body.dispatchEvent(new PointerEvent('pointerdown', {bubbles:true})); persistenceTest.tick()`);
  await until('!document.querySelector("[role=tooltip]")');
  await click('通用');
  await evaluate(`document.querySelector('button[aria-label="日志显示说明"]').click(); persistenceTest.tick()`);
  assert.equal(await evaluate(`document.querySelector('button[aria-label="日志显示说明"]').closest('[data-settings-collapse]').querySelector('button').getAttribute('aria-expanded')`), 'false');
  await evaluate(`document.body.dispatchEvent(new PointerEvent('pointerdown', {bubbles:true})); persistenceTest.tick()`);
  await click('日志显示');
  await delay(200);
  assert.ok(await evaluate('document.body.innerText.includes("英文字体")'));
  console.log('PASS settings help: hover, focus, click, Escape isolation, outside dismissal, viewport bounds and independent collapse');
}, { timeoutMs: 180000 });
